
def handler_error(error):
    print('Um erro ocorreu :',error)